### ISSUE TITLE
Segmentation fault following context deadline exceeded

### ISSUE THREAD

**Issue by srhb** [cloudhut/kminion#80] opened 2021-04-12 07:51 UTC
This error is preceeded by a lot of "context deadline exceeded" that I've cut out. Maybe the broker was slow to respond? Regardless, kafka-minion ends up crashing on commit 4f4b8c5f2d3fe7c5a4277558fbc9157a0f7273b5

```
[...]
{"level":"error","ts":"2021-04-11T23:38:26.772Z","msg":"failed to fetch low water marks","error":"context deadline exceeded"}
{"level":"error","ts":"2021-04-11T23:38:26.772Z","msg":"failed to fetch low water marks","error":"context deadline exceeded"}
{"level":"error","ts":"2021-04-11T23:38:26.773Z","msg":"failed to get topic configs","error":"failed to request metadata: context deadline exceeded"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x80955b]

goroutine 193461419 [running]:
github.com/twmb/franz-go/pkg/kgo.(*describeGroupsSharder).shard(0xc003a8e120, 0xccfea0, 0xc0060fe540, 0xcd5f00, 0xc0011fdb30, 0xc000f1f3a8, 0x756ea1ebff4aa6, 0xe5a4044f45e2fd78, 0x400, 0x400, ...)
        /build/source/vendor/github.com/twmb/franz-go/pkg/kgo/client.go:1516 +0x19b
github.com/twmb/franz-go/pkg/kgo.(*Client).handleShardedReq.func2(0x0, 0xcd5f00, 0xc0011fdb30)
        /build/source/vendor/github.com/twmb/franz-go/pkg/kgo/client.go:1266 +0x111
github.com/twmb/franz-go/pkg/kgo.(*Client).handleShardedReq(0xc000089000, 0xccfea0, 0xc0060fe540, 0xcd5f00, 0xc0011fdb30, 0xc0060fe540, 0xc000089000, 0xc0011fe600, 0x2d0)
        /build/source/vendor/github.com/twmb/franz-go/pkg/kgo/client.go:1332 +0x2b9
github.com/twmb/franz-go/pkg/kgo.(*Client).shardedRequest(0xc000089000, 0xccfea0, 0xc0060fe540, 0xcd5f00, 0xc0011fdb30, 0x0, 0x0, 0x0, 0x0)
        /build/source/vendor/github.com/twmb/franz-go/pkg/kgo/client.go:652 +0x1c6
github.com/twmb/franz-go/pkg/kgo.(*Client).Request(0xc000089000, 0xccff60, 0xc000928360, 0xcd5f00, 0xc0011fdb30, 0x30, 0xb62320, 0xc000355701, 0xc0011fdb30)
        /build/source/vendor/github.com/twmb/franz-go/pkg/kgo/client.go:490 +0x57
github.com/twmb/franz-go/pkg/kmsg.(*DescribeGroupsRequest).RequestWith(0xc0011fdb30, 0xccff60, 0xc000928360, 0xcc2a60, 0xc000089000, 0x0, 0x0, 0xc0017986c0)
        /build/source/vendor/github.com/twmb/franz-go/pkg/kmsg/generated.go:11541 +0x5f
github.com/cloudhut/kminion/v2/minion.(*Service).DescribeConsumerGroups(0xc000362000, 0xccff60, 0xc000928360, 0xc0018933e0, 0x0, 0x0)
        /build/source/minion/describe_consumer_groups.go:61 +0x1f9
github.com/cloudhut/kminion/v2/prometheus.(*Exporter).collectConsumerGroups(0xc00035c0c0, 0xccff60, 0xc000928360, 0xc00568e0c0, 0xae6a01)
        /build/source/prometheus/collect_consumer_groups.go:15 +0x6a
github.com/cloudhut/kminion/v2/prometheus.(*Exporter).Collect(0xc00035c0c0, 0xc00568e0c0)
        /build/source/prometheus/exporter.go:196 +0x2af
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /build/source/vendor/github.com/prometheus/client_golang/prometheus/registry.go:446 +0x1a2
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /build/source/vendor/github.com/prometheus/client_golang/prometheus/registry.go:538 +0xe8e
```

**Comment by weeco** [comment] 2021-04-12 07:58
Hey @srhb ,
thanks for reporting. This panic happens inside of the Kafka lib we're using and I haven't seen it before. I passed it to the author for further help.

I haven't seen metadata requests or watermark requests fail due to an actual timeout though. I think metadata is always cached in each broker. That scrape would probably have failed or not export many of the exported metricses. This should obviously not cause a panic though 👍

**Comment by srhb** [comment] 2021-04-13 06:09
I seem to be able to provoke this by doing a rolling restart of the kafka cluster, too. That's certainly new, as kafka-minion used to be able to continue functioning during a broker outage, but now it stops responding and eventually panics with the above trace.

**Comment by weeco** [comment] 2021-04-13 07:33
@srhb That's most likely caused by the rewrite where we also migrated to a new Kafka client, which is imo way better though. The lib author found the issue and pushed a fix already: https://github.com/twmb/franz-go/commit/56b83089447b1c1ec39346a48bc8b9f87cd6452d . He said he'll be committing a bit more code around this and then I'll update KMinion to use the updated lib.

I'll keep you posted here

**Comment by srhb** [comment] 2021-04-13 08:47
Lovely, thank you!

**Closed** 2021-04-21 07:51 UTC
Labels: bug

**Comment by weeco** [comment] 2021-04-21 07:59
Hey @srhb ,
I updated the lib and tagged a new release right afterwards: https://github.com/cloudhut/kminion/releases/tag/v2.1.0
